adding simple travis.yml file
project-flogo/ml pull request #21
Opened 2020-03-18 19:24 UTC by abramvandergeest

adding a travis file to test all of the inference activities test cases.

2020-03-19 17:29 UTC, lixingwang requested changes
Let's remove depth:1 which will cause issues when there are multiple commits in PR.  let's just remove it and keep it as default.

2020-03-19 17:51 UTC, abramvandergeest commented
Thanks Tracy, I have removed git and depth.

2020-03-19 18:14 UTC, lixingwang approved these changes

2020-03-20 14:45 UTC, mellistibco approved these changes

2020-03-20 14:49 UTC, merged